zeebe:


  client:
    broker.gatewayAddress: 127.0.0.1:26500
    security.plaintext: true

    worker:
      hazelcast:
        connection: localhost:5701
        connectionTimeout: PT30S

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    expose-request-attributes: true

  data:
    web:
      pageable:
        default-page-size: 10

server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: utf-8

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.monitor: DEBUG
    com.hazelcast: WARN

white-label:
  logo.path: img/logo.png
  custom:
    title: Zeebe Simple Monitor
    css.path: css/custom.css
    js.path: js/custom.js
